// ============================================================
//  KIKI.COM — Mock Data Layer
// ============================================================

const CITIES = [
  { name: "Mumbai",         slug: "mumbai",         region: "Maharashtra",  count: 1286 },
  { name: "Delhi",          slug: "delhi",          region: "Delhi (NCT)",  count: 985  },
  { name: "Bengaluru",      slug: "bengaluru",      region: "Karnataka",    count: 847  },
  { name: "Hyderabad",      slug: "hyderabad",      region: "Telangana",    count: 724  },
  { name: "Chennai",        slug: "chennai",        region: "Tamil Nadu",   count: 652  },
  { name: "Kolkata",        slug: "kolkata",        region: "West Bengal",  count: 518  },
  { name: "Pune",           slug: "pune",           region: "Maharashtra",  count: 421  },
  { name: "Ahmedabad",      slug: "ahmedabad",      region: "Gujarat",      count: 385  },
  { name: "Jaipur",         slug: "jaipur",         region: "Rajasthan",    count: 298  },
  { name: "Surat",          slug: "surat",          region: "Gujarat",      count: 247  },
  { name: "Lucknow",        slug: "lucknow",        region: "Uttar Pradesh",count: 219  },
  { name: "Kanpur",         slug: "kanpur",         region: "Uttar Pradesh",count: 185  },
  { name: "Nagpur",         slug: "nagpur",         region: "Maharashtra",  count: 162  },
  { name: "Indore",         slug: "indore",         region: "Madhya Pradesh",count: 143 },
  { name: "Bhopal",         slug: "bhopal",         region: "Madhya Pradesh",count: 129 },
  { name: "Patna",          slug: "patna",          region: "Bihar",        count: 98   },
  { name: "Vadodara",       slug: "vadodara",       region: "Gujarat",      count: 87   },
  { name: "Ludhiana",       slug: "ludhiana",       region: "Punjab",       count: 74   },
  { name: "Agra",           slug: "agra",           region: "Uttar Pradesh",count: 61   },
  { name: "Nashik",         slug: "nashik",         region: "Maharashtra",  count: 54   },
];

const SERVICES = [
  { id: "gfe",       label: "GFE",              category: "experience" },
  { id: "massage",   label: "Massage",           category: "wellness"   },
  { id: "dinner",    label: "Dinner Date",       category: "social"     },
  { id: "travel",    label: "Travel Companion",  category: "social"     },
  { id: "overnight", label: "Overnight",         category: "duration"   },
  { id: "weekend",   label: "Weekend Trips",     category: "duration"   },
  { id: "duo",       label: "Duo / Trio",        category: "special"    },
  { id: "bdsm",      label: "BDSM",              category: "special"    },
  { id: "tantric",   label: "Tantric",           category: "wellness"   },
  { id: "striptease",label: "Striptease",        category: "experience" },
  { id: "roleplay",  label: "Role Play",         category: "experience" },
  { id: "webcam",    label: "Webcam",            category: "online"     },
  { id: "sexting",   label: "Sexting",           category: "online"     },
  { id: "erotic_massage", label: "Erotic Massage", category: "wellness" },
  { id: "domination", label: "Domination",       category: "special"    },
];

const REVIEWS_POOL = [
  { author: "Marc T.",  rating: 5, comment: "Absolutely wonderful, very professional and elegant. Highly recommended!", date: "2026-06-15" },
  { author: "Julien R.",rating: 5, comment: "Perfect experience, exactly as described. Will definitely book again.", date: "2026-06-20" },
  { author: "Pierre D.",rating: 4, comment: "Great company, very pleasant evening. Punctual and discreet.", date: "2026-05-30" },
  { author: "Alex B.",  rating: 5, comment: "Stunning lady, great conversation. The best experience I've had.", date: "2026-07-01" },
  { author: "Thomas M.",rating: 4, comment: "Very kind and attentive. Made me feel completely at ease.", date: "2026-06-10" },
  { author: "Kevin L.", rating: 5, comment: "Simply breathtaking. Everything was perfect from start to finish.", date: "2026-07-05" },
  { author: "Sébastien",rating: 3, comment: "Good experience overall, a bit rushed but very charming.", date: "2026-05-20" },
  { author: "Nicolas",  rating: 5, comment: "An unforgettable evening. Discreet, elegant, and incredibly warm.", date: "2026-06-28" },
];

const PROFILES = [
  // ---- DIAMOND TIER ----
  {
    id: 1, name: "Valentina", age: 24, city: "Mumbai", citySlug: "mumbai",
    tier: "diamond", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: true,
    primaryPhoto: "extracted_images/100_imageye___-_imgi_18_kho-63889980333588-2103213618.webp",
    photos: [
      "extracted_images/101_imgi_12_49408ed62002a78c3c0cfbe3f7ac147c26f07.webp",
      "extracted_images/102_imgi_1_30189IMG-20260309-WA0000.webp",
      "extracted_images/103_imgi_39_40426IMG-20260126-WA0006.webp",
    ],
    videoThumb: "extracted_images/104_imgi_70_361.webp",
    shortDesc: "Elite companion for distinguished gentlemen. Luxury experience guaranteed.",
    description: "Namaste! I am Valentina, an elite independent companion based in the heart of Mumbai. I offer refined companionship for distinguished gentlemen who appreciate beauty, intelligence, and discretion. My warm personality and natural elegance make every encounter truly unforgettable. I'm available for dinner dates, cultural events, travel, and private encounters.",
    services: ["gfe","dinner","travel","overnight","striptease"],
    languages: ["Hindi", "English", "Italian"],
    phone: "+91 98123 45678", whatsapp: true, email: "valentina@kiki.com",
    incallRate: "₹10,000/hr", outcallRate: "₹12,000/hr",
    availability: { mon: "All day", tue: "All day", wed: "14h-23h", thu: "All day", fri: "All day", sat: "All day", sun: "12h-22h" },
    ethnicity: "European", bodyType: "Slim & toned", hairColor: "Brunette", height: "170cm", cupSize: "C",
    reviewCount: 28, avgRating: 4.9, viewCount: 5420, createdAt: "2025-09-01",
    reviews: [REVIEWS_POOL[0], REVIEWS_POOL[5], REVIEWS_POOL[7]],
    verifications: ["photo","id","phone","video"],
  },
  {
    id: 2, name: "Isabella", age: 26, city: "Delhi", citySlug: "delhi",
    tier: "diamond", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: true,
    primaryPhoto: "extracted_images/105_model5_imgi28319_66036930.webp",
    photos: [
      "extracted_images/106_imageye___-_imgi_20_kho-63895536292352-2103213618.webp",
      "extracted_images/107_imgi_13_30185IMG-20250812-WA0006.webp",
    ],
    videoThumb: "extracted_images/108_imgi_21_34350IMG-20260305-WA0201.webp",
    shortDesc: "Stunning brunette. High-end companionship in Delhi.",
    description: "Welcome! I am Isabella, a sophisticated and passionate companion. With my natural beauty and warm smile, I guarantee a memorable experience filled with genuine connection and mutual pleasure. I speak three languages and love fine dining, art galleries, and intimate conversations.",
    services: ["gfe","dinner","overnight","massage","roleplay"],
    languages: ["Hindi", "English", "Spanish"],
    phone: "+91 98234 56789", whatsapp: true, email: null,
    incallRate: "₹9,000/hr", outcallRate: "₹11,000/hr",
    availability: { mon: "10h-22h", tue: "10h-22h", wed: "All day", thu: "10h-22h", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "Latin", bodyType: "Curvy", hairColor: "Brunette", height: "165cm", cupSize: "D",
    reviewCount: 41, avgRating: 4.8, viewCount: 6830, createdAt: "2025-07-15",
    reviews: [REVIEWS_POOL[1], REVIEWS_POOL[3], REVIEWS_POOL[6]],
    verifications: ["photo","id","phone"],
  },
  {
    id: 3, name: "Sophia", age: 28, city: "Bengaluru", citySlug: "bengaluru",
    tier: "diamond", gender: "female",
    isOnline: false, isVerified: true, isNew: false, hasVideo: true,
    primaryPhoto: "extracted_images/109_model5_imgi113404_1b2b6ace.webp",
    photos: ["extracted_images/10_imgi_160_443.webp"],
    videoThumb: "extracted_images/110_imageye___-_imgi_11_15246IMG-20250902-WA0001.webp",
    shortDesc: "Refined and cultured. Your perfect companion in Bengaluru.",
    description: "Hello, I'm Sophia. An educated, refined companion who genuinely enjoys the company of interesting men. I'm passionate about art, music, and great cuisine. Let me show you the best of Bengaluru while being your ideal companion for any occasion.",
    services: ["gfe","dinner","travel","tantric","duo"],
    languages: ["Hindi", "English"],
    phone: "+91 98345 67890", whatsapp: false, email: "sophia@kiki.com",
    incallRate: "₹8,000/hr", outcallRate: "₹10,000/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "All day" },
    ethnicity: "European", bodyType: "Athletic", hairColor: "Blonde", height: "172cm", cupSize: "B",
    reviewCount: 19, avgRating: 4.7, viewCount: 3210, createdAt: "2025-11-20",
    reviews: [REVIEWS_POOL[4], REVIEWS_POOL[7]],
    verifications: ["photo","id"],
  },
  {
    id: 4, name: "Ariana", age: 23, city: "Hyderabad", citySlug: "hyderabad",
    tier: "diamond", gender: "female",
    isOnline: true, isVerified: true, isNew: true, hasVideo: false,
    primaryPhoto: "extracted_images/111_imgi_103_394.webp",
    photos: ["extracted_images/112_imgi_16_71172IMG-20231127-WA0170_043653.webp"],
    videoThumb: null,
    shortDesc: "Young, passionate, and incredibly beautiful. Premium lifestyle.",
    description: "Hi, I'm Ariana! New to Hyderabad and ready to make your stay truly unforgettable. Young, energetic, and full of passion — I love meeting new people and creating memorable experiences.",
    services: ["gfe","dinner","striptease","massage"],
    languages: ["English", "Telugu", "Hindi"],
    phone: "+91 98456 78901", whatsapp: true, email: null,
    incallRate: "₹9,500/hr", outcallRate: "₹12,000/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "All day" },
    ethnicity: "Middle Eastern", bodyType: "Slim", hairColor: "Black", height: "163cm", cupSize: "C",
    reviewCount: 3, avgRating: 5.0, viewCount: 1840, createdAt: "2026-06-15",
    reviews: [REVIEWS_POOL[3]],
    verifications: ["photo","phone"],
  },
  {
    id: 5, name: "Camille", age: 30, city: "Chennai", citySlug: "chennai",
    tier: "diamond", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: true,
    primaryPhoto: "extracted_images/113_imgi_2_4258238833IMG-20260304-WA0011.webp",
    photos: ["extracted_images/114_imgi_55_346.webp"],
    videoThumb: "extracted_images/115_model5_imgi133g8_edcec7cb.webp",
    shortDesc: "Elegance personified. Art & passion lover.",
    description: "I am Camille, an authentic elegant woman with charm and class. I am the perfect dinner companion, travel partner, or intimate encounter for the discerning gentleman who values quality above all else.",
    services: ["gfe","dinner","overnight","weekend","travel"],
    languages: ["Tamil", "English", "German"],
    phone: "+91 98567 78901", whatsapp: true, email: "camille@kiki.com",
    incallRate: "₹10,500/hr", outcallRate: "₹13,500/hr",
    availability: { mon: "12h-23h", tue: "12h-23h", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "European", bodyType: "Slim & toned", hairColor: "Brunette", height: "168cm", cupSize: "B",
    reviewCount: 55, avgRating: 4.9, viewCount: 9120, createdAt: "2024-12-01",
    reviews: [REVIEWS_POOL[0], REVIEWS_POOL[1], REVIEWS_POOL[5]],
    verifications: ["photo","id","phone","video"],
  },
  {
    id: 6, name: "Natasha", age: 25, city: "Kolkata", citySlug: "kolkata",
    tier: "diamond", gender: "female",
    isOnline: false, isVerified: true, isNew: false, hasVideo: true,
    primaryPhoto: "extracted_images/116_imageye___-_imgi_14_kho-63890674611730-2103213618.webp",
    photos: ["extracted_images/117_imgi_113_404.webp"],
    videoThumb: "extracted_images/118_imgi_182_219129.webp",
    shortDesc: "Exotic beauty in the cultural hub of Kolkata.",
    description: "Hello darling! I am Natasha, originally from Delhi, now living in the beautiful city of Kolkata. I am passionate, attentive, and utterly devoted to making our time together perfect in every way.",
    services: ["gfe","massage","erotic_massage","tantric","overnight"],
    languages: ["Bengali", "Hindi", "English"],
    phone: "+91 98678 90123", whatsapp: true, email: null,
    incallRate: "₹9,000/hr", outcallRate: "₹11,000/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "All day" },
    ethnicity: "Eastern European", bodyType: "Slim", hairColor: "Blonde", height: "175cm", cupSize: "C",
    reviewCount: 33, avgRating: 4.8, viewCount: 4560, createdAt: "2025-08-10",
    reviews: [REVIEWS_POOL[2], REVIEWS_POOL[6]],
    verifications: ["photo","id"],
  },

  // ---- GOLD TIER ----
  {
    id: 7, name: "Charlotte", age: 27, city: "Pune", citySlug: "pune",
    tier: "gold", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/119_imgi_31_246151764578199230.webp",
    photos: ["extracted_images/11_imgi_27_529871764578199180.webp"],
    videoThumb: null,
    shortDesc: "Warm, sensual, and utterly charming. Pune city companion.",
    description: "Bonjour! I'm Charlotte, a warm and sensual companion in Pune. I love long walks, fine food, and meaningful connections. Let me be your guide to the pleasure and beauty of this city.",
    services: ["gfe","dinner","massage","overnight"],
    languages: ["Marathi", "English", "French"],
    phone: "+91 98789 01234", whatsapp: false, email: "charlotte@kiki.com",
    incallRate: "₹6,000/hr", outcallRate: "₹8,000/hr",
    availability: { mon: "All day", tue: "All day", wed: "Off", thu: "All day", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "European", bodyType: "Athletic", hairColor: "Brunette", height: "166cm", cupSize: "C",
    reviewCount: 14, avgRating: 4.6, viewCount: 2340, createdAt: "2026-02-14",
    reviews: [REVIEWS_POOL[4]],
    verifications: ["photo","phone"],
  },
  {
    id: 8, name: "Léa", age: 22, city: "Ahmedabad", citySlug: "ahmedabad",
    tier: "gold", gender: "female",
    isOnline: true, isVerified: false, isNew: true, hasVideo: false,
    primaryPhoto: "extracted_images/120_imgi_142_425.webp",
    photos: ["extracted_images/121_imgi_22_47048IMG-20260226-WA0006.webp"],
    videoThumb: null,
    shortDesc: "Young and playful. All-natural girl next door energy.",
    description: "Hi! I'm Léa, a young and spontaneous girl who loves adventure and new experiences. Based in Ahmedabad, I offer a fun, relaxed, and authentic companionship experience. Fresh, natural, and full of life!",
    services: ["gfe","massage","striptease","roleplay"],
    languages: ["English", "Gujarati", "Hindi"],
    phone: "+91 98890 12345", whatsapp: true, email: null,
    incallRate: "₹5,000/hr", outcallRate: "₹7,000/hr",
    availability: { mon: "14h-22h", tue: "14h-22h", wed: "All day", thu: "14h-22h", fri: "All day", sat: "All day", sun: "14h-22h" },
    ethnicity: "European", bodyType: "Petite", hairColor: "Blonde", height: "160cm", cupSize: "B",
    reviewCount: 2, avgRating: 5.0, viewCount: 980, createdAt: "2026-07-01",
    reviews: [],
    verifications: ["photo"],
  },
  {
    id: 9, name: "Anaïs", age: 29, city: "Jaipur", citySlug: "jaipur",
    tier: "gold", gender: "female",
    isOnline: false, isVerified: true, isNew: false, hasVideo: true,
    primaryPhoto: "extracted_images/122_imgi_43_334.webp",
    photos: ["extracted_images/123_imgi_8_301.webp"],
    videoThumb: "extracted_images/124_model5_imgi57348_6f88526a.webp",
    shortDesc: "Royal city goddess. Passionate and intense.",
    description: "Bonjour! I'm Anaïs from Jaipur. With my warm temperament and passionate nature, I offer an intense and genuine connection. Life is too short for boring encounters — let's make ours extraordinary.",
    services: ["gfe","dinner","bdsm","domination","overnight"],
    languages: ["English", "Hindi", "Italian"],
    phone: "+91 98901 23456", whatsapp: true, email: null,
    incallRate: "₹7,000/hr", outcallRate: "₹9,000/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "12h-20h" },
    ethnicity: "Mediterranean", bodyType: "Curvy", hairColor: "Black", height: "164cm", cupSize: "D",
    reviewCount: 22, avgRating: 4.5, viewCount: 3780, createdAt: "2025-10-05",
    reviews: [REVIEWS_POOL[2], REVIEWS_POOL[7]],
    verifications: ["photo","id"],
  },
  {
    id: 10, name: "Eva", age: 31, city: "Surat", citySlug: "surat",
    tier: "gold", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/125_imageye___-_imgi_3_celebrity-escorts-india-919120202066-bollywood-film-pc-1761989018-1.webp",
    photos: ["extracted_images/126_imgi_14_83446IMG-20260306-WA0095.webp"],
    videoThumb: null,
    shortDesc: "Sophisticated North-South India beauty. Cross-state elegance.",
    description: "Namaste! I am Eva, a bilingual companion straddling two cultures with effortless grace. Whether you prefer a sophisticated North Indian experience or a traditional Southern approach, I adapt perfectly to your desires.",
    services: ["gfe","dinner","travel","weekend","massage"],
    languages: ["Hindi", "Gujarati", "English"],
    phone: "+91 99012 34567", whatsapp: false, email: "eva@kiki.com",
    incallRate: "₹6,500/hr", outcallRate: "₹8,500/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "All day" },
    ethnicity: "European", bodyType: "Slim", hairColor: "Red", height: "169cm", cupSize: "B",
    reviewCount: 18, avgRating: 4.7, viewCount: 2890, createdAt: "2025-12-15",
    reviews: [REVIEWS_POOL[4], REVIEWS_POOL[1]],
    verifications: ["photo","id","phone"],
  },
  {
    id: 11, name: "Roxane", age: 25, city: "Lucknow", citySlug: "lucknow",
    tier: "gold", gender: "female",
    isOnline: false, isVerified: true, isNew: true, hasVideo: false,
    primaryPhoto: "extracted_images/127_imgi_24_38761IMG-20260310-WA0003.webp",
    photos: ["extracted_images/128_imgi_46_63173vip-(1).webp"],
    videoThumb: null,
    shortDesc: "Sweet and naughty city belle. New in Lucknow.",
    description: "Hello! I'm Roxane, new in Lucknow but definitely not inexperienced! I'm a playful mix of sweet and naughty, offering a fun companionship experience for gentlemen who know what they want.",
    services: ["gfe","massage","striptease","duo"],
    languages: ["Hindi", "English"],
    phone: "+91 99123 45679", whatsapp: true, email: null,
    incallRate: "₹5,500/hr", outcallRate: "₹7,500/hr",
    availability: { mon: "Off", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "14h-22h" },
    ethnicity: "European", bodyType: "Athletic", hairColor: "Blonde", height: "167cm", cupSize: "B",
    reviewCount: 1, avgRating: 5.0, viewCount: 540, createdAt: "2026-07-08",
    reviews: [],
    verifications: ["photo"],
  },
  {
    id: 12, name: "Marine", age: 34, city: "Kanpur", citySlug: "kanpur",
    tier: "gold", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: true,
    primaryPhoto: "extracted_images/129_imgi_98_389.webp",
    photos: ["extracted_images/12_imgi_50_323312817aerocity-escorts-100-premium-escort-indian-escort-in-new-delhi-13932962_original.webp"],
    videoThumb: "extracted_images/130_model5_imgi79370_14eded45.webp",
    shortDesc: "Mature, elegant, and utterly sensual companion.",
    description: "I am Marine, a mature and confident woman who knows exactly what she wants and how to make her companion feel like the most important person in the world. Experience authentic companionship in Kanpur.",
    services: ["gfe","dinner","overnight","erotic_massage","tantric"],
    languages: ["Hindi", "English"],
    phone: "+91 99234 56789", whatsapp: true, email: "marine@kiki.com",
    incallRate: "₹6,800/hr", outcallRate: "₹8,500/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "European", bodyType: "Full figured", hairColor: "Brunette", height: "163cm", cupSize: "D",
    reviewCount: 29, avgRating: 4.6, viewCount: 4120, createdAt: "2025-06-20",
    reviews: [REVIEWS_POOL[0], REVIEWS_POOL[3]],
    verifications: ["photo","id"],
  },

  // ---- SILVER TIER ----
  {
    id: 13, name: "Luna", age: 21, city: "Nagpur", citySlug: "nagpur",
    tier: "silver", gender: "female",
    isOnline: true, isVerified: false, isNew: true, hasVideo: false,
    primaryPhoto: "extracted_images/131_imageye___-_imgi_7_4417020250316_231816.webp",
    photos: ["extracted_images/132_imgi_105_396.webp"],
    videoThumb: null,
    shortDesc: "Young, sun-kissed local girl. Fresh debut.",
    description: "Hi sweetie! I am Luna, a 21-year-old beauty new to escorting and living in vibrant Nagpur. I'm natural, spontaneous, and genuinely excited to meet you. Student by day, companion by night!",
    services: ["gfe","massage","striptease"],
    languages: ["Marathi", "English", "Hindi"],
    phone: "+91 99345 67891", whatsapp: true, email: null,
    incallRate: "₹3,800/hr", outcallRate: "₹5,000/hr",
    availability: { mon: "18h-23h", tue: "Off", wed: "18h-23h", thu: "18h-23h", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "European", bodyType: "Petite", hairColor: "Brunette", height: "158cm", cupSize: "B",
    reviewCount: 0, avgRating: null, viewCount: 340, createdAt: "2026-07-10",
    reviews: [],
    verifications: ["photo"],
  },
  {
    id: 14, name: "Zara", age: 26, city: "Indore", citySlug: "indore",
    tier: "silver", gender: "female",
    isOnline: false, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/133_imgi_16_75356IMG-20260314-WA0111.webp",
    photos: ["extracted_images/134_imgi_2_809453480967513IMG-20260226-WA0007.webp"],
    videoThumb: null,
    shortDesc: "Mixed-heritage beauty. Warm and open-minded.",
    description: "Hey! I'm Zara. Mixed heritage, full of warmth and curiosity. I love making genuine connections with people from all walks of life. Indore is my city and I know all its hidden gems — let me be your guide.",
    services: ["gfe","massage","dinner","roleplay"],
    languages: ["Hindi", "English"],
    phone: "+91 99456 78902", whatsapp: true, email: null,
    incallRate: "₹4,500/hr", outcallRate: "₹5,800/hr",
    availability: { mon: "All day", tue: "All day", wed: "14h-22h", thu: "All day", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "Mixed", bodyType: "Curvy", hairColor: "Black", height: "162cm", cupSize: "D",
    reviewCount: 8, avgRating: 4.4, viewCount: 1540, createdAt: "2026-01-20",
    reviews: [REVIEWS_POOL[4]],
    verifications: ["photo","id"],
  },
  {
    id: 15, name: "Elena", age: 24, city: "Bhopal", citySlug: "bhopal",
    tier: "silver", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/135_imgi_56_347.webp",
    photos: ["extracted_images/136_model5_imgi135418_09dfd0fe.webp"],
    videoThumb: null,
    shortDesc: "Sweet and sensual beauty. Bhopal companion.",
    description: "Namaste! I am Elena, a sweet beauty in Bhopal. I am gentle, feminine, and deeply passionate. My beautiful eyes and warm smile will make you forget all your worries.",
    services: ["gfe","massage","tantric","erotic_massage"],
    languages: ["Hindi", "English"],
    phone: "+91 99567 89013", whatsapp: false, email: "elena@kiki.com",
    incallRate: "₹4,200/hr", outcallRate: "₹5,500/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "14h-20h" },
    ethnicity: "Eastern European", bodyType: "Slim", hairColor: "Blonde", height: "168cm", cupSize: "C",
    reviewCount: 6, avgRating: 4.5, viewCount: 1230, createdAt: "2025-11-30",
    reviews: [REVIEWS_POOL[2]],
    verifications: ["photo","phone"],
  },
  {
    id: 16, name: "Jade", age: 23, city: "Patna", citySlug: "patna",
    tier: "silver", gender: "female",
    isOnline: false, isVerified: false, isNew: true, hasVideo: false,
    primaryPhoto: "extracted_images/137_imageye___-_imgi_14_kho-63895277278591-2103213618.webp",
    photos: ["extracted_images/138_imgi_115_406.webp"],
    videoThumb: null,
    shortDesc: "Sweet city beauty. Natural and carefree.",
    description: "Hello! I'm Jade from Patna, your sweet companion. I'm natural, carefree, and genuinely fun to be around. Whether it's a coffee date, a walk along the river, or a private encounter — I'm your girl.",
    services: ["gfe","massage","striptease"],
    languages: ["Hindi", "English"],
    phone: "+91 99678 90124", whatsapp: true, email: null,
    incallRate: "₹4,000/hr", outcallRate: "₹5,200/hr",
    availability: { mon: "Off", tue: "Off", wed: "18h-23h", thu: "18h-23h", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "European", bodyType: "Slim", hairColor: "Brunette", height: "164cm", cupSize: "B",
    reviewCount: 0, avgRating: null, viewCount: 210, createdAt: "2026-07-11",
    reviews: [],
    verifications: [],
  },
  {
    id: 17, name: "Mia", age: 28, city: "Vadodara", citySlug: "vadodara",
    tier: "silver", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/139_imgi_186_218554.webp",
    photos: ["extracted_images/13_imgi_144_221902.webp"],
    videoThumb: null,
    shortDesc: "Confident and classy companion. Art world insider.",
    description: "Hi! I'm Mia. I work in the art world during the day and offer my companionship to select gentlemen in the evenings in Vadodara. Intelligent conversation, beautiful presence, genuine warmth — everything you need for a perfect evening.",
    services: ["gfe","dinner","massage"],
    languages: ["English", "Gujarati", "Hindi"],
    phone: "+91 99789 01235", whatsapp: false, email: null,
    incallRate: "₹4,800/hr", outcallRate: "₹6,000/hr",
    availability: { mon: "18h-23h", tue: "18h-23h", wed: "18h-23h", thu: "18h-23h", fri: "18h-23h", sat: "All day", sun: "Off" },
    ethnicity: "European", bodyType: "Slim & toned", hairColor: "Brunette", height: "170cm", cupSize: "B",
    reviewCount: 11, avgRating: 4.6, viewCount: 1890, createdAt: "2026-03-01",
    reviews: [REVIEWS_POOL[1]],
    verifications: ["photo","id"],
  },
  {
    id: 18, name: "Alexia", age: 32, city: "Ludhiana", citySlug: "ludhiana",
    tier: "silver", gender: "female",
    isOnline: false, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/140_imgi_31_77265IMG-20260309-WA0042.webp",
    photos: ["extracted_images/141_imgi_5_9752062388IMG-20260303-WA0035.webp"],
    videoThumb: null,
    shortDesc: "Experienced companion. No games, just pleasure.",
    description: "Je m'appelle Alexia. At 32, I am at the height of my confidence, sensuality, and experience in Ludhiana. I don't play games and I don't waste time. If you know what you want and appreciate a woman who delivers — call me.",
    services: ["gfe","bdsm","domination","massage","erotic_massage"],
    languages: ["Punjabi", "Hindi", "English"],
    phone: "+91 99890 12346", whatsapp: true, email: null,
    incallRate: "₹5,000/hr", outcallRate: "₹6,500/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "14h-22h", sun: "Off" },
    ethnicity: "European", bodyType: "Curvy", hairColor: "Black", height: "165cm", cupSize: "E",
    reviewCount: 16, avgRating: 4.5, viewCount: 2670, createdAt: "2025-09-15",
    reviews: [REVIEWS_POOL[6], REVIEWS_POOL[7]],
    verifications: ["photo"],
  },

  // ---- TRANS ----
  {
    id: 19, name: "Bianca TS", age: 27, city: "Agra", citySlug: "agra",
    tier: "gold", gender: "trans",
    isOnline: true, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/142_model5_imgi152435_bc131997.webp",
    photos: ["extracted_images/143_imageye___-_imgi_16_kho-63892428821262-2103213618.webp"],
    videoThumb: null,
    shortDesc: "Stunning trans goddess in Agra. Unforgettable experience.",
    description: "Oi! I am Bianca, a trans companion living in Agra. I am fully operational, post-op, and completely stunning. I offer a truly unique and unforgettable experience for open-minded gentlemen.",
    services: ["gfe","massage","overnight","tantric"],
    languages: ["English", "Hindi", "Spanish"],
    phone: "+91 99012 34568", whatsapp: true, email: null,
    incallRate: "₹7,500/hr", outcallRate: "₹9,500/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "All day" },
    ethnicity: "Latin", bodyType: "Slim & toned", hairColor: "Brunette", height: "178cm", cupSize: "C",
    reviewCount: 24, avgRating: 4.9, viewCount: 4320, createdAt: "2025-10-01",
    reviews: [REVIEWS_POOL[3], REVIEWS_POOL[5]],
    verifications: ["photo","id"],
  },
  {
    id: 20, name: "Sofia TS", age: 24, city: "Nashik", citySlug: "nashik",
    tier: "silver", gender: "trans",
    isOnline: false, isVerified: false, isNew: true, hasVideo: false,
    primaryPhoto: "extracted_images/144_imgi_145_428.webp",
    photos: ["extracted_images/145_imgi_22_88943IMG-20260228-WA0020.webp"],
    videoThumb: null,
    shortDesc: "Young trans beauty. Sweet and attentive.",
    description: "Hi babe! I am Sofia, a young trans girl, new in Nashik. I am sweet, attentive, and very passionate. I love making my partners feel truly special.",
    services: ["gfe","massage","striptease"],
    languages: ["English", "Hindi", "Marathi"],
    phone: "+91 99123 45680", whatsapp: true, email: null,
    incallRate: "₹5,000/hr", outcallRate: "₹6,500/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "Latin", bodyType: "Slim", hairColor: "Blonde", height: "172cm", cupSize: "B",
    reviewCount: 1, avgRating: 5.0, viewCount: 410, createdAt: "2026-07-05",
    reviews: [],
    verifications: ["photo"],
  },

  // ---- ONLINE NOW ----
  {
    id: 21, name: "Priya", age: 26, city: "Mumbai", citySlug: "mumbai",
    tier: "gold", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/146_imgi_44_22569IMG-20260228-WA0023.webp",
    photos: ["extracted_images/147_imgi_8_94887IMG-20260305-WA0035.webp"],
    videoThumb: null,
    shortDesc: "Exotic Indian beauty. Kama Sutra mastery.",
    description: "Namaste! I am Priya, an exotic beauty from Mumbai, residing in Mumbai. I bring the ancient art of sensual massage and companionship to the sophistication of Mumbai.",
    services: ["gfe","massage","tantric","erotic_massage"],
    languages: ["Hindi", "English", "Marathi"],
    phone: "+91 99234 56790", whatsapp: true, email: null,
    incallRate: "₹6,200/hr", outcallRate: "₹8,000/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "All day" },
    ethnicity: "Asian", bodyType: "Curvy", hairColor: "Black", height: "160cm", cupSize: "D",
    reviewCount: 15, avgRating: 4.7, viewCount: 2890, createdAt: "2025-12-01",
    reviews: [REVIEWS_POOL[0]],
    verifications: ["photo","id"],
  },
  {
    id: 22, name: "Chloé", age: 25, city: "Faridabad", citySlug: "faridabad",
    tier: "gold", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/148_model5_imgi66357_93d81c8e.webp",
    photos: ["extracted_images/149_imageye___-_imgi_3_kho-63900206264721-2103213618.webp"],
    videoThumb: null,
    shortDesc: "Fiery beauty. Full of passion.",
    description: "Coucou! I'm Chloé from Faridabad — fiery, passionate, and full of energy. I love life and I love sharing good moments with charming people. Let's create something beautiful together.",
    services: ["gfe","massage","dinner","striptease"],
    languages: ["Hindi", "English"],
    phone: "+91 99345 67892", whatsapp: false, email: null,
    incallRate: "₹6,000/hr", outcallRate: "₹7,800/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "All day" },
    ethnicity: "Mediterranean", bodyType: "Athletic", hairColor: "Brunette", height: "165cm", cupSize: "C",
    reviewCount: 20, avgRating: 4.8, viewCount: 3450, createdAt: "2025-08-20",
    reviews: [REVIEWS_POOL[5]],
    verifications: ["photo","id"],
  },
  {
    id: 23, name: "Viktoria", age: 29, city: "Ghaziabad", citySlug: "ghaziabad",
    tier: "silver", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/14_imgi_22_49663IMG_20260227_070814_685.webp",
    photos: ["extracted_images/150_imgi_150_433.webp"],
    videoThumb: null,
    shortDesc: "Czech beauty in Ghaziabad. Cultured and discreet.",
    description: "Hello! I am Viktoria, currently based in Ghaziabad. I am educated, cultured, and genuinely enjoy meeting interesting men. Discretion and respect are my top priorities.",
    services: ["gfe","dinner","massage"],
    languages: ["English", "Hindi"],
    phone: "+91 99456 78903", whatsapp: true, email: null,
    incallRate: "₹4,500/hr", outcallRate: "₹5,800/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "14h-22h" },
    ethnicity: "Eastern European", bodyType: "Slim", hairColor: "Blonde", height: "171cm", cupSize: "C",
    reviewCount: 9, avgRating: 4.3, viewCount: 1560, createdAt: "2026-02-01",
    reviews: [],
    verifications: ["photo"],
  },

  // ---- WITH VIDEO ----
  {
    id: 24, name: "Jasmine", age: 27, city: "Rajkot", citySlug: "rajkot",
    tier: "silver", gender: "female",
    isOnline: false, isVerified: true, isNew: false, hasVideo: true,
    primaryPhoto: "extracted_images/151_imgi_24_68885IMG-20260307-WA0032.webp",
    photos: ["extracted_images/152_imgi_47_338.webp"],
    videoThumb: "extracted_images/153_imgi_9_24791IMG_20260206_120351_750.webp",
    shortDesc: "Mixed beauty. Spicy and sensual.",
    description: "Hello! I'm Jasmine, now in Rajkot. I'm a spicy mix of warmth and elegance. Watch my video to see just how special I am before you book.",
    services: ["gfe","massage","striptease","webcam"],
    languages: ["Gujarati", "Hindi", "English"],
    phone: "+91 99567 89014", whatsapp: true, email: null,
    incallRate: "₹5,000/hr", outcallRate: "₹6,500/hr",
    availability: { mon: "All day", tue: "All day", wed: "Off", thu: "All day", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "North African", bodyType: "Curvy", hairColor: "Black", height: "162cm", cupSize: "D",
    reviewCount: 12, avgRating: 4.5, viewCount: 2340, createdAt: "2025-11-10",
    reviews: [REVIEWS_POOL[2]],
    verifications: ["photo","id"],
  },
  {
    id: 25, name: "Tania", age: 30, city: "Amritsar", citySlug: "amritsar",
    tier: "gold", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: true,
    primaryPhoto: "extracted_images/154_model5_imgi84375_4eab4ad7.webp",
    photos: ["extracted_images/155_imageye___-_imgi_7_kho-63893525961722-2103213618.webp"],
    videoThumb: "extracted_images/156_imgi_125_416.webp",
    shortDesc: "Intellectual and passionate companion.",
    description: "Hello. I am Tania, based in Amritsar. I am your most passionate and intellectually stimulating companion. I believe the best encounters engage both the mind and the body.",
    services: ["gfe","dinner","overnight","roleplay","tantric"],
    languages: ["Punjabi", "Hindi", "English"],
    phone: "+91 99678 90125", whatsapp: false, email: "tania@kiki.com",
    incallRate: "₹7,000/hr", outcallRate: "₹9,000/hr",
    availability: { mon: "19h-23h", tue: "19h-23h", wed: "Off", thu: "19h-23h", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "European", bodyType: "Slim & toned", hairColor: "Red", height: "167cm", cupSize: "B",
    reviewCount: 21, avgRating: 4.8, viewCount: 3780, createdAt: "2025-07-01",
    reviews: [REVIEWS_POOL[0], REVIEWS_POOL[7]],
    verifications: ["photo","id","phone"],
  },

  // ---- MOST REVIEWED ----
  {
    id: 26, name: "Dominique", age: 35, city: "Mumbai", citySlug: "mumbai",
    tier: "diamond", gender: "female",
    isOnline: false, isVerified: true, isNew: false, hasVideo: true,
    primaryPhoto: "extracted_images/157_imgi_19_63336cb38320c2998c410e613f0f7afe7744be25beae818749513a5ebba526b034c2c.0.webp",
    photos: ["extracted_images/158_imgi_36_PHOTO-2024-09-30-13-07-46.webp"],
    videoThumb: "extracted_images/159_imgi_65_356.webp",
    shortDesc: "Mumbai's most reviewed escort. 8 years experience.",
    description: "I am Dominique, Mumbai's most reviewed and trusted independent escort with 8 years of experience. My reviews speak for themselves. If you want guaranteed perfection, you've found it.",
    services: ["gfe","dinner","travel","overnight","weekend","bdsm","domination"],
    languages: ["English", "Hindi", "French"],
    phone: "+91 99789 01236", whatsapp: true, email: "dominique@kiki.com",
    incallRate: "₹12,500/hr", outcallRate: "₹16,000/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "All day" },
    ethnicity: "European", bodyType: "Slim & toned", hairColor: "Brunette", height: "169cm", cupSize: "C",
    reviewCount: 89, avgRating: 4.9, viewCount: 15840, createdAt: "2017-01-01",
    reviews: [REVIEWS_POOL[0], REVIEWS_POOL[1], REVIEWS_POOL[3], REVIEWS_POOL[5], REVIEWS_POOL[7]],
    verifications: ["photo","id","phone","video"],
  },
  {
    id: 27, name: "Amélie", age: 29, city: "Delhi", citySlug: "delhi",
    tier: "gold", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/15_imgi_43_63853IMG-20251201-WA0065.webp",
    photos: ["extracted_images/160_model5_imgi17308_c4b47770.webp"],
    videoThumb: null,
    shortDesc: "Delhi's sweetheart. Consistently 5 stars.",
    description: "Hello! I'm Amélie, and I'm proud to be one of Delhi's most loved companions. My secret? Genuine warmth, real passion, and always going the extra mile to make you feel special.",
    services: ["gfe","massage","dinner","striptease","tantric"],
    languages: ["Hindi", "English"],
    phone: "+91 99890 12347", whatsapp: true, email: null,
    incallRate: "₹6,500/hr", outcallRate: "₹8,500/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "12h-20h" },
    ethnicity: "European", bodyType: "Athletic", hairColor: "Blonde", height: "166cm", cupSize: "C",
    reviewCount: 46, avgRating: 4.8, viewCount: 7230, createdAt: "2024-09-15",
    reviews: [REVIEWS_POOL[4], REVIEWS_POOL[6]],
    verifications: ["photo","id"],
  },

  // ---- MOST POPULAR ----
  {
    id: 28, name: "Stefania", age: 26, city: "Bengaluru", citySlug: "bengaluru",
    tier: "diamond", gender: "female",
    isOnline: true, isVerified: true, isNew: false, hasVideo: true,
    primaryPhoto: "extracted_images/161_imageye___-_imgi_19_2083154842Screenshot_20251209_204926.webp",
    photos: ["extracted_images/162_imgi_130_nimage-22.webp"],
    videoThumb: "extracted_images/163_imgi_1_83687IMG-20260223-WA0019.webp",
    shortDesc: "Bengaluru's most viewed profile. Italian temptress.",
    description: "Ciao! I'm Stefania, an Italian model and companion who captured Bengaluru's heart. I'm the most viewed profile on this site for a reason — come see for yourself.",
    services: ["gfe","dinner","overnight","travel","striptease"],
    languages: ["Italian", "English", "Hindi"],
    phone: "+91 99012 34569", whatsapp: true, email: "stefania@kiki.com",
    incallRate: "₹11,000/hr", outcallRate: "₹14,500/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "European", bodyType: "Athletic", hairColor: "Brunette", height: "173cm", cupSize: "C",
    reviewCount: 67, avgRating: 4.9, viewCount: 22140, createdAt: "2024-06-01",
    reviews: [REVIEWS_POOL[0], REVIEWS_POOL[1], REVIEWS_POOL[2], REVIEWS_POOL[5]],
    verifications: ["photo","id","phone","video"],
  },
  {
    id: 29, name: "Nora", age: 25, city: "Hyderabad", citySlug: "hyderabad",
    tier: "gold", gender: "female",
    isOnline: false, isVerified: true, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/164_imgi_3_56276geniune-Tamil-girl-hot-girl-videocall-service-camsex-phone-sex_1.webp",
    photos: ["extracted_images/165_imgi_72_42517IMG-20260314-WA0004.webp"],
    videoThumb: null,
    shortDesc: "Trending profile of the month in Hyderabad.",
    description: "Hi! I'm Nora and apparently I've been trending all month in Hyderabad! I'm flattered and ready to meet all my new fans. Come discover why everyone is talking about me.",
    services: ["gfe","massage","dinner","striptease","overnight"],
    languages: ["English", "Telugu", "Hindi"],
    phone: "+91 99123 45681", whatsapp: true, email: null,
    incallRate: "₹6,800/hr", outcallRate: "₹8,500/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "All day" },
    ethnicity: "North African", bodyType: "Curvy", hairColor: "Black", height: "163cm", cupSize: "D",
    reviewCount: 31, avgRating: 4.7, viewCount: 8540, createdAt: "2025-05-10",
    reviews: [REVIEWS_POOL[3], REVIEWS_POOL[6]],
    verifications: ["photo","id"],
  },
  {
    id: 30, name: "Lydia", age: 33, city: "Chennai", citySlug: "chennai",
    tier: "silver", gender: "female",
    isOnline: true, isVerified: false, isNew: false, hasVideo: false,
    primaryPhoto: "extracted_images/166_model5_imgi33324_59201e8a.webp",
    photos: ["extracted_images/167_imageye___-_imgi_21_kho-63889499807447-2103213618.webp"],
    videoThumb: null,
    shortDesc: "Seasoned companion. Real reviews, real results.",
    description: "Hello, I am Lydia. I've been doing this for 5 years and I have the experience and confidence that only time can build in Chennai. My clients come back again and again — that's the real review you need.",
    services: ["gfe","massage","bdsm","erotic_massage"],
    languages: ["English", "Tamil", "Hindi"],
    phone: "+91 99234 56791", whatsapp: false, email: null,
    incallRate: "₹4,500/hr", outcallRate: "₹6,000/hr",
    availability: { mon: "All day", tue: "All day", wed: "All day", thu: "All day", fri: "All day", sat: "All day", sun: "Off" },
    ethnicity: "European", bodyType: "Full figured", hairColor: "Red", height: "164cm", cupSize: "F",
    reviewCount: 34, avgRating: 4.4, viewCount: 5670, createdAt: "2021-03-01",
    reviews: [REVIEWS_POOL[7]],
    verifications: ["photo"],
  },
];

// ---- HELPER FUNCTIONS ----
function getProfilesByTier(tier, limit = 6) {
  return PROFILES.filter(p => p.tier === tier).slice(0, limit);
}
function getOnlineProfiles(limit = 8) {
  return PROFILES.filter(p => p.isOnline).slice(0, limit);
}
function getNewProfiles(limit = 6) {
  return PROFILES.filter(p => p.isNew).slice(0, limit);
}
function getProfilesWithVideo(limit = 6) {
  return PROFILES.filter(p => p.hasVideo).slice(0, limit);
}
function getMostReviewed(limit = 6) {
  return [...PROFILES].sort((a, b) => b.reviewCount - a.reviewCount).slice(0, limit);
}
function getMostPopular(limit = 6) {
  return [...PROFILES].sort((a, b) => b.viewCount - a.viewCount).slice(0, limit);
}
function getProfileById(id) {
  return PROFILES.find(p => p.id === parseInt(id));
}
function getProfilesByCity(citySlug, limit = 12) {
  return PROFILES.filter(p => p.citySlug === citySlug).slice(0, limit);
}
function getSimilarProfiles(profile, limit = 4) {
  return PROFILES.filter(p => p.id !== profile.id && (p.citySlug === profile.citySlug || p.tier === profile.tier)).slice(0, limit);
}

// Stats
const SITE_STATS = {
  totalListings: 6348,
  onlineNow: PROFILES.filter(p => p.isOnline).length,
  verifiedProfiles: PROFILES.filter(p => p.isVerified).length,
  totalCities: CITIES.length,
};
